### ISSUE TITLE
How to get rrd?

### ISSUE THREAD

**Issue by RetroRipper** [EnterpriseVE/eve2pve-api-php#1]
Hello why is this not working?

  $retArr = $client->getNodes()->get("ns3365239")->getQemu()->get(100)->getRrd()->getResponse()->data;
  echo "\n" . $retArr['data']['vmid'];

And how do you stop a vps and how do you create a vps.

**Comment by franklupo** [comment]
Hi,

For **rrd maxcpu** example:

> $retArr = $client->getNodes()->get("ns3365239")->getQemu()->get(100)->getRrd()->rrd('maxcpu', 'day');
> var_dump($retArr->getResponse()->data);

Return image and file name.

For rrddata
> $retArr = $client->getNodes()->get("pve1")->getQemu()->get(100)->getRrddata()->rrddata('day');
> var_dump($retArr->getResponse()->data);
return array JSON

For start vm
> $retArr = $client->getNodes()->get("pve1")->getQemu()->get(101)->getStatus()->getStart()->vmStart();
return task
example string(58) "UPID:pve1:00003295:0032034A:59F0A6F1:qmstart:101:root@pam:"

For stop vm
>  $retArr = $client->getNodes()->get("pve1")->getQemu()->get(101)->getStatus()->getStop()->vmStop(); 
return task

best regards
