### ISSUE TITLE
RRD not loading Image

### ISSUE THREAD

**Issue by RetroRipper** [EnterpriseVE/eve2pve-api-php#2]
Hello i use this code.

`$retArr = $client->getNodes()->get("ns3365239")->getQemu()->get(101)->getRrd()->rrd('maxcpu', 'day')->getResponse();
print_r($retArr);`

but i get thit output

`Array ( [data] => )`

**Comment by franklupo** [comment]
Hi,
what version do you use?

**Comment by RetroRipper** [comment]
Hello i have update the proxmox version now the base64 image is loading but how do i get the image from it.


`$retArr = $client->getNodes()->get("ns3365239")->getQemu()->get(101)->getRrd()->rrd('maxcpu', 'day')->getResponse();
echo'<img style="width: 100%;100%;" src="data:image/png;base64,'.base64_encode($retArr['data']['image']).'" />`


Image of the base64 code
http://prntscr.com/h4jjjr

Image of the website.
http://prntscr.com/h4jjx2

why is the image not loading?

**Comment by RetroRipper** [comment]
Hello,

no is not working.

http://prntscr.com/h4jr5h

**Comment by franklupo** [comment]
Hello,
http://php.net/manual/en/function.imagecreatefromstring.php

**Comment by RetroRipper** [comment]
Still not working? i am using Virtual Environment 5.1-36

**Comment by franklupo** [comment]
`
$base64=base64_encode($retArr['data']['image']);
echo "<img src='data:image/png;base64,{$base64}' \>";
`
this?

**Comment by RetroRipper** [comment]
No it is not working.

**Comment by franklupo** [comment]
Hello,
I found the problem.

**Comment by franklupo** [comment]
```
//image rrd
  $client->setResponseType('png');
  echo "<img src='{$client->getNodes()->get("pve1")->getRrd()->rrd('cpu','day')->getResponse()}' \>";
/
/set default
  $client->setResponseType('json');
```

**Comment by RetroRipper** [comment]
Nice i have fix it to but you need to to utf8_decode the image data, like this than is it workin.

[<img style="width: 100%;" src="data:image/png;base64, '.base64_encode(utf8_decode($retArr['data']['image'])).'" />](url)
