### ISSUE TITLE
Create a Qemu VM

### ISSUE THREAD

**Issue by RetroRipper** [EnterpriseVE/eve2pve-api-php#3]
Hello,

How do you create a Qemu  VM?

Tom Lammers

**Comment by franklupo** [comment]
Hi Tom,
for creating a Qemu VM:

`
$vmid=101;
$client->getNodes()->get("pve1")->getQemu()->createVm(vmid);
`

The variables $hostpciN,$ideN,$netN,$numaN.$parallelN,$sataN,$scsiN, $serialN, $unusedN,$usbN $virtioN are array. 

Eg. 
$ideN= [ "ide0" => "none,media=cdrom"];
$virtioN= [ "virtio1" => "local=25,format=qcow2"];

/**
 * Create or restore a virtual machine.
 * **param** int $vmid The (unique) ID of the VM.
 * **param** bool $acpi Enable/disable ACPI.
 * **param** bool $agent Enable/disable Qemu GuestAgent.
 * **param** string $archive The backup file.
 * **param** string $args Arbitrary arguments passed to kvm.
 * **param** bool $autostart Automatic restart after crash (currently ignored).
 * **param** int $balloon Amount of target RAM for the VM in MB. Using zero disables the ballon driver.
 * **param** string $bios Select BIOS implementation.
 *   Enum: seabios,ovmf
 * **param** string $boot Boot on floppy (a), hard disk (c), CD-ROM (d), or network (n).
 * **param** string $bootdisk Enable booting from specified disk.
 * **param** string $cdrom This is an alias for option -ide2
 * **param** int $cores The number of cores per socket.
 * **param** string $cpu Emulated CPU type.
 * **param** int $cpulimit Limit of CPU usage.
 * **param** int $cpuunits CPU weight for a VM.
 * **param** string $description Description for the VM. Only used on the configuration web interface. This is saved as comment inside the configuration file.
 * **param** bool $force Allow to overwrite existing VM.
 * **param** bool $freeze Freeze CPU at startup (use 'c' monitor command to start execution).
 * **param** array $hostpciN Map host PCI devices into guest.
 * **param** string $hotplug Selectively enable hotplug features. This is a comma separated list of hotplug features: 'network', 'disk', 'cpu', 'memory' and 'usb'. Use '0' to disable hotplug completely. Value '1' is an alias for the default 'network,disk,usb'.
 * **param** string $hugepages Enable/disable hugepages memory.
 *   Enum: any,2,1024
 * **param** array $ideN Use volume as IDE hard disk or CD-ROM (n is 0 to 3).
 * **param** string $keyboard Keybord layout for vnc server. Default is read from the '/etc/pve/datacenter.conf' configuration file.
 *   Enum: de,de-ch,da,en-gb,en-us,es,fi,fr,fr-be,fr-ca,fr-ch,hu,is,it,ja,lt,mk,nl,no,pl,pt,pt-br,sv,sl,tr
 * **param** bool $kvm Enable/disable KVM hardware virtualization.
 * **param** bool $localtime Set the real time clock to local time. This is enabled by default if ostype indicates a Microsoft OS.
 * **param** string $lock Lock/unlock the VM.
 *   Enum: migrate,backup,snapshot,rollback
 * **param** string $machine Specific the Qemu machine type.
 * **param** int $memory Amount of RAM for the VM in MB. This is the maximum available memory when you use the balloon device.
 * **param** int $migrate_downtime Set maximum tolerated downtime (in seconds) for migrations.
 * **param** int $migrate_speed Set maximum speed (in MB/s) for migrations. Value 0 is no limit.
 * **param** string $name Set a name for the VM. Only used on the configuration web interface.
 * **param** array $netN Specify network devices.
 * **param** bool $numa Enable/disable NUMA.
 * **param** array $numaN NUMA topology.
 * **param** bool $onboot Specifies whether a VM will be started during system bootup.
 * **param** string $ostype Specify guest operating system.
 *   Enum: other,wxp,w2k,w2k3,w2k8,wvista,win7,win8,win10,l24,l26,solaris
 * **param** array $parallelN Map host parallel devices (n is 0 to 2).
 * **param** string $pool Add the VM to the specified pool.
 * **param** bool $protection Sets the protection flag of the VM. This will disable the remove VM and remove disk operations.
 * **param** bool $reboot Allow reboot. If set to '0' the VM exit on reboot.
 * **param** array $sataN Use volume as SATA hard disk or CD-ROM (n is 0 to 5).
 * **param** array $scsiN Use volume as SCSI hard disk or CD-ROM (n is 0 to 13).
 * **param** string $scsihw SCSI controller model
 *   Enum: lsi,lsi53c810,virtio-scsi-pci,virtio-scsi-single,megasas,pvscsi
 * **param** array $serialN Create a serial device inside the VM (n is 0 to 3)
 * **param** int $shares Amount of memory shares for auto-ballooning. The larger the number is, the more memory this VM gets. Number is relative to weights of all other running VMs. Using zero disables auto-ballooning
 * **param** string $smbios1 Specify SMBIOS type 1 fields.
 * **param** int $smp The number of CPUs. Please use option -sockets instead.
 * **param** int $sockets The number of CPU sockets.
 * **param** string $startdate Set the initial date of the real time clock. Valid format for date are: 'now' or '2006-06-17T16:01:21' or '2006-06-17'.
 * **param** string $startup Startup and shutdown behavior. Order is a non-negative number defining the general startup order. Shutdown in done with reverse ordering. Additionally you can set the 'up' or 'down' delay in seconds, which specifies a delay to wait before the next VM is started or stopped.
 * **param** string $storage Default storage.
 * **param** bool $tablet Enable/disable the USB tablet device.
 * **param** bool $tdf Enable/disable time drift fix.
 * **param** bool $template Enable/disable Template.
 * **param** bool $unique Assign a unique random ethernet address.
 * **param** array $unusedN Reference to unused volumes. This is used internally, and should not be modified manually.
 * **param** array $usbN Configure an USB device (n is 0 to 4).
 * **param** int $vcpus Number of hotplugged vcpus.
 * **param** string $vga Select the VGA type.
 *   Enum: std,cirrus,vmware,qxl,serial0,serial1,serial2,serial3,qxl2,qxl3,qxl4
 * **param** array $virtioN Use volume as VIRTIO hard disk (n is 0 to 15).
 * **param** string $vmstatestorage Default storage for VM state volumes/files.
 * **param** string $watchdog Create a virtual hardware watchdog device.
 * **return** Result
*/

public function createVm($vmid, $acpi = null, $agent = null, $archive = null, $args = null, $autostart = null, $balloon = null, $bios = null, $boot = null, $bootdisk = null, $cdrom = null, $cores = null, $cpu = null, $cpulimit = null, $cpuunits = null, $description = null, $force = null, $freeze = null, $hostpciN = null, $hotplug = null, $hugepages = null, $ideN = null, $keyboard = null, $kvm = null, $localtime = null, $lock = null, $machine = null, $memory = null, $migrate_downtime = null, $migrate_speed = null, $name = null, $netN = null, $numa = null, $numaN = null, $onboot = null, $ostype = null, $parallelN = null, $pool = null, $protection = null, $reboot = null, $sataN = null, $scsiN = null, $scsihw = null, $serialN = null, $shares = null, $smbios1 = null, $smp = null, $sockets = null, $startdate = null, $startup = null, $storage = null, $tablet = null, $tdf = null, $template = null, $unique = null, $unusedN = null, $usbN = null, $vcpus = null, $vga = null, $virtioN = null, $vmstatestorage = null, $watchdog = null)

**Comment by RetroRipper** [comment]
Nice tnx!

And how do i clone a VM?

**Comment by franklupo** [comment]
Hi Tom,
in source is documentated all.

$newId=101;
$client->getNodes()->get("pve1")->getQemu()->get(100)->getClone()->cloneVm($newId);

`
        /**
         * Create a copy of virtual machine/template.
         * **param** int $newid VMID for the clone.
         * **param** string $description Description for the new VM.
         * **param** string $format Target format for file storage.
         *   Enum: raw,qcow2,vmdk
         * **param** bool $full Create a full copy of all disk. This is always done when you clone a normal VM. For VM templates, we try to create a linked clone by default.
         * **param** string $name Set a name for the new VM.
         * **param** string $pool Add the new VM to the specified pool.
         * **param** string $snapname The name of the snapshot.
         * **param** string $storage Target storage for full clone.
         * **param** string $target Target node. Only allowed if the original VM is on shared storage.
         * **return** Result
         */

        public function cloneVm($newid, $description = null, $format = null, $full = null, $name = null, $pool = null, $snapname = null, $storage = null, $target = null)
`

**Comment by franklupo** [comment]
Hi Tom,
i improve documentation in code.

Best regards

**Comment by RetroRipper** [comment]
Nice tnx!

But why is this not working?

`$client->getNodes()->get($getDatarow['node'])->getQemu()->get(101)->getConfig()->getRest($cores = 2);`

It dont update the hardware

**Comment by franklupo** [comment]
Hi Tom,

Name parameter in PHP not working.
https://wiki.php.net/rfc/named_params

Specify null value in parameter position.

**Comment by RetroRipper** [comment]
Why is it not updating the config of the emu?
This is not working...


```
$current = ['memory' => 1024];
$client->getNodes()->get($getDatarow['node'])->getQemu()->get(500)->getConfig()->vmConfig($current);
```

What is wrong?  Can you make a example how to edit the config?

**Comment by franklupo** [comment]
Hi,
$client->getNodes()->get($getDatarow['node'])->getQemu()->get(101)->getConfig()->updateVm(,,,)

doc;
updateVm($acpi = null, $agent = null, $args = null, $autostart = null, $balloon = null, $bios = null, $boot = null, $bootdisk = null, $cdrom = null, $cores = null, $cpu = null, $cpulimit = null, $cpuunits = null, $delete = null, $description = null, $digest = null, $force = null, $freeze = null, $hostpciN = null, $hotplug = null, $hugepages = null, $ideN = null, $keyboard = null, $kvm = null, $localtime = null, $lock = null, $machine = null, $memory = null, $migrate_downtime = null, $migrate_speed = null, $name = null, $netN = null, $numa = null, $numaN = null, $onboot = null, $ostype = null, $parallelN = null, $protection = null, $reboot = null, $revert = null, $sataN = null, $scsiN = null, $scsihw = null, $serialN = null, $shares = null, $skiplock = null, $smbios1 = null, $smp = null, $sockets = null, $startdate = null, $startup = null, $tablet = null, $tdf = null, $template = null, $unusedN = null, $usbN = null, $vcpus = null, $vga = null, $virtioN = null, $vmstatestorage = null, $watchdog = null)

**Comment by YWatchman** [comment]
How to retrieve a list of ISO's on a disk?

**Comment by YWatchman** [comment]
Found it out myself, I forgot to include an extra login because my constructor wouldn't pick it up.

**Comment by edvkossmann** [comment]
Hi Guys,

How do i create a hard drive with 50 GB?


thx
ralf
